### ISSUE TITLE
11/18/2015 meeting (agenda and discussion)

### ISSUE THREAD

**Issue by willbarton** [cfpb/back-end#11]
Because we didn't really get a lot of movement after the last meeting, I'd like to focus on one particular area: Django. 

I've seen the term "normal Django app" bandied about as if it had meaning. If it does, I'm not entirely sure what that meaning is in our particular context, and I think it'd be something very useful to have defined before the new backend fellows start in January.

I don't really think this needs to be a survey of existing Django apps so much as a set of guides to what our pragmatic ideal might be. This is what someone would read if they're creating new apps.

I think this will focus in on a few specific areas (in no particular order):
- Configuration 
  
  Is it handled in the same way we've already discussed (#1)?
- Basic app structure
  
  Generally (as far as I've seen), we create apps that provide APIs. What does that look like organizationally? Is it just basic Django? Are there any particular concerns we should be aware of?
- Common dependencies
  
  What dpeendencies do we already have available for common tasks (like Django Rest Framework for API creation). I don't want to discourage experimentation with new libraries, etc, but I want to make it easy to say, I'm creating an API, Django Rest Framework is already installed in production and that's what a bunch of other projects are using, I'll use that.
- Common patterns
  
  Building on the last point, would it be useful to have a some common patterns? Again, there are only so many ways to create an API with Django, so is there a general pattern we can define for that? I'm also thinking of Mike Brown's presentation yesterday and the need to ensure you know what your foreign keys have been up to.
- Fixtures and testing
  
  Is there anything particular about our approach to testing Django apps beyond plain Django unit tests? I know we use `mock` relatively frequently, and mocking can be somewhat confusing to get your head around at first.
- Security best-practices
  
  What are the things we should be aware of and things we should be doing in all our Django apps?
- Integration with our Django project
  
  This isn't, in my mind, a step-by-step for how to integrate into a larger Django project (and how we handle shared resources, etc), but rather a collection of concerns and possible approaches to consider. 
- Front end integration (#5)
  
  This is a problem every project that provides a front-end is going to struggle with. How do we do it?
- Internationalization (#9)
  
  We should be doing this whereever possible. Is this just straight-up Django internationalization? 
- Source control (#8)
- Performance/Good ORMing

Some very special and unique snowflakes (_cough_eRegs_cough_) might be too esoteric for some or all of these to apply, but I'm looking for useful starting points for someone starting to create a Django app at CFPB. It would be nice to put some of this into a Django template, but in my experience, every software project is that little bit different. I think written guides empower a developer to approach their particular project needs with our approach to Django in mind.

Thoughts? In today's meeting, I'd like to ask for two things:
1. Agreement on areas of Django, like the list above, where we can draw guidelines around what a normal CFPB Django app should be like.
2. Volunteers to tackle those areas.

Specifics about each of these areas can be discussed in issues to preserve the discussion for reference later.

**Comment by marcesher** [comment]
@willbarton In light of yesterday's tech talk, I'd probably add one more: mindfulness of Django ORM and being a good ORM citizen. I suspect for most of our django apps, interaction with the database is going to be the single greatest source of potential performance problems

**Comment by willbarton** [comment]
:+1:

**Comment by willbarton** [comment]
Prioritization:
1. Frontend integration - Django template as a starting point that integrates frontend build flow? This is the largest single pain-point for our Django projects at the moment and should be a priority.

This will be the subject of a Dev COP discussion involving both front-ends and back-ends.
